GET http://localhost:3000/locations

###

GET http://localhost:3000/locations/60b789a9ac740f3ff45ee013

###

POST http://localhost:3000/locations
Content-Type: application/json

{
    "name":"test1235",
    "country" : "sweden",
    "text":"text",
    "imageURL":"some url"
}

###

PATCH http://localhost:3000/locations/60a4d022d8f5c644b80cd6e5
Content-Type: application/json

{
    "name":"test2",
    "imageURL" : ["img1","img2"]
}

###

DELETE http://localhost:3000/locations/60b789a9ac740f3ff45ee013

###

DELETE http://localhost:3000/locations