GET http://localhost:3000/locations

###

GET http://localhost:3000/locations/60b8f02280f0163c70d89396

###

POST http://localhost:3000/locations
Content-Type: application/json

{
    "name":"test1235",
    "country" : "sweden",
    "text":"text",
    "imageURL":"some url"
}

###

PATCH http://localhost:3000/locations/60b8f604217ece36b05fdb5a
Content-Type: application/json

{
    "name":"test3",
    "imageURL" : ["img1","img2"]
}

###

DELETE http://localhost:3000/locations/60b789a9ac740f3ff45ee013

###

DELETE http://localhost:3000/locations